#!/bin/bash

DOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# vim
ln -s ${DOTDIR}/.vimrc ~/.vimrc

# tmux
ln -s ${DOTDIR}/.tmux.conf ~/.tmux.conf

# zsh
ln -s ${DOTDIR}/.zshrc ~/.zshrc
ln -s ${DOTDIR}/.aliases ~/.aliases

# git
ln -s ${DOTDIR}/.gitconfig ~/.gitconfig
ln -s ${DOTDIR}/.gitignore_global ~/.gitignore_global

# ack
ln -s ${DOTDIR}/.ackrc ~/.ackrc

# iTerm
# Specify the preferences directory
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/.dotfiles/iterm_profile"
# Tell iTerm2 to use the custom preferences in the directory
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

